ignore:
  - "tests/*"
  - "benches/*"
  - "examples/*"
  - "docs/*"
  - "crates/issundb-examples/*"
  - "crates/issundb-py/*"
  - "crates/issundb-node/*"
  - "benchmarks/*"
  - "scripts/*"
  - "crates/issundb-cli/src/main.rs"
