//! Raw FFI bindings to SuiteSparse:GraphBLAS (Apache-2.0).
//!
//! The C library source is vendored as the `external/GraphBLAS` git submodule and
//! built from source by `build.rs` as a position-independent static library with a
//! dynamically linked OpenMP runtime, so the resulting objects link cleanly into
//! shared objects (the Python extension `cdylib`). Bindings are
//! generated by `bindgen` over `Include/GraphBLAS.h`.
//!
//! This crate replaces the non-permissive `suitesparse_graphblas_sys`. It exposes
//! the raw C API; the safe surface lives in `issundb-graphblas`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
// bindgen emits `u128` for the C `long double`/complex helpers (`creall`, etc.),
// which Rust flags as not-FFI-safe. The engine never calls those helpers; silence
// the noise from the generated bindings.
#![allow(improper_ctypes)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
