//! Raw FFI bindings to SuiteSparse:GraphBLAS.
//!
//! The C library source is vendored as the `external/GraphBLAS` Git submodule and
//! built from source by `build.rs` as a position-independent static library with a
//! dynamically linked OpenMP runtime, so the resulting objects link cleanly into
//! shared objects (like the Python extension's `cdylib` build). The OpenMP runtime is resolved
//! per platform (`libgomp` with GCC on Linux, `libomp` with Apple Clang on macOS,
//! and `vcomp` with MSVC on Windows). Bindings are generated by `bindgen` over
//! `Include/GraphBLAS.h`.
//!
//! This crate exposes the raw C API; the safe surface (the usable Rust API)
//! lives in `issundb-graphblas`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
// Bindgen emits `u128` for the C `long double`/complex helpers (`creall`, etc.),
// which Rust flags as not FFI-safe. The engine never calls those helpers; so we silence
// the noise from the generated bindings.
#![allow(improper_ctypes)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
